workflows:
  version: 2
  test:
    jobs:
      - java-8
      - java-9
      - java-10
      - java-11
      - java-12

version: 2
shared: &shared
  working_directory: ~/repo
  environment:
    # Customize the JVM maximum heap limit
    GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m"
  steps:
    - checkout
    # Run all tests
    - run: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - run: ./mvnw test -B

jobs:
  java-8:
    docker:
      - image: openjdk:8
    <<: *shared

  java-9:
    docker:
      - image: openjdk:9
    <<: *shared

  java-10:
    docker:
      - image: openjdk:10
    <<: *shared

  java-11:
    docker:
      - image: openjdk:11
    <<: *shared

  java-12:
    docker:
      - image: openjdk:12
    <<: *shared
